# AviumUI Configs
AVIUM_MAINTAINER := ReLimus
AVIUM_BUILDTYPE := Unoffical
AVIUM_VERSION_APPEND_TIME_OF_DAY := false

# AviumUI Settings
AVIUM_SETTINGS_SOC_MODEL_NAME := SM8550
AVIUM_SETTINGS_DEVICE_CODENAME := m2468

# GMS
WITH_GMS := true

# Google Sans
TARGET_USES_GSANS := true

# Spoof Props
AVIUM_FORCE_SET_FAKE_PROP := true